---
author: "patrick.unicorn"
output:
  html_document:
    css: ../../css/main.css
    highlight: null
    theme: null
---

读《A Little Java A Few Pattern》
===

* * *

本文的目的不在于翻译《A Little Java A Few Pattern》，而在于对书中比较”怪异、晦涩”的代码片段进行解读。如果对本书感兴趣，可以移步[这里][1]。


[1]: http://a-little-java-a-few-patterns.readthedocs.io/zh_CN/latest/index.html

## NumD

出自书中的第四章，如下：

```

```

需要将其与之前翻译的Lambda表达式联系，其表达自然数的方式与Lambda表达式如出一辙。

补充。


## PizzaD 

### 功能

一台生产Pizza的机器，生成pizza的过程是先编制好所有的面皮和料：

1. Pizza有两部分组成：一个面皮和多个顶料
2. 订料包括：奶酪、凤尾鱼、橄榄、香肠
3. 订料支持任意组合

在实际生产前，可以增减顶料支持如下操作：

1. 支持将已经放入的所有凤尾鱼顶料移除
2. 支持在已经放入的所有凤尾鱼顶料上加奶酪
3. 支持将已经放入的所有凤尾鱼顶料替换为奶酪

### 实现方式一

出自书中的第六章，如下：


```
//比萨饼
abstract class PizzaD { 

    //去除比萨饼中的凤尾鱼顶料(因为太咸了)
    abstract PizzaD remA(); 
    
    //在凤尾鱼顶料上加上奶酪顶料(这样会盖住凤尾鱼的咸味)
    abstract PizzaD topAwC(); 
    
    //将所有的凤尾鱼顶料换成奶酪顶料
    abstract PizzaD subAbC(); 
}

// 面包皮，注意与其他顶料在构造函数，以及实现上的区别
class Crust extends PizzaD { 
    PizzaD subAbC(){
        return new Crust();
    }
    PizzaD topAwC(){
        return new Crust();
    }
    PizzaD subAbC(){
        return new Crust();
    }
}

// 下面是各种顶料
class Cheese extends PizzaD { //奶酪
    PizzaD p;
    Cheese (PizzaD _p) {
        p = _p;
    }
    PizzaD remA(){
        return new Cheese(p.remA());
    }
    PizzaD topAwC(){
        return new Cheese(p.topAwC());
    }
    PizzaD subAbC(){
        return new Cheese(p.subAbC());
    }
}

// 橄榄
class Olive extends PizzaD { 
    PizzaD p;
    Olive (PizzaD _p) {
        p = _p;
    }
    PizzaD remA(){
        return new Olive(p.remA());
    }
    PizzaD topAwC(){
        return new Olive(p.topAwC());
    }
    PizzaD subAbC(){
        return new Olive(p.subAbC());
    }
}

// 凤尾鱼
class Anchovy extends PizzaD { 
    PizzaD p;
    Anchovy (PizzaD _p) {
        p = _p;
    }
    PizzaD remA(){
        return p.remA();
    }
    PizzaD topAwC(){
        return new Cheese(new Anchovy(p.topAwC()));
    }
    PizzaD subAbC(){
        return new Cheese(p.subAbC());
    }
}

// 香肠
class Sausage extends PizzaD { 
    PizzaD p;
    Sausage (PizzaD _p) {
        p = _p;
    }
    PizzaD remA(){
        return new Sausage(p.remA());
    }
    PizzaD topAwC(){
        return new Sausage(p.topAwC());
    }
    PizzaD subAbC(){
        return new Sausage(p.subAbC());
    }
}
```

用例：

```
public static void main(String[] args) {
	// 创建奶酪pizza
	PizzaD p0 = new Cheese(new Crust());

	// 创建凤尾鱼-奶酪pizza
	PizzaD p1 = new Anchovy(new Cheese(new Crust()));
	// 等于new Cheese(new Crust())
	p1.remA(); 

	// 创建香肠-奶酪pizza
	PizzaD p2 = new Sausage(new Cheese(new Crust()));
	
	// 等于new Sausage(new Cheese(new Crust()))
	p2.remA(); 
}
```

这种设计方法其实更函数式化编程，在三个方法的实现中，利用“构造函数”实现了“递归迭代”的思想。比如remA方法，调用它的时候会“向上遍历”所有的“pizzaD”类型实例，并调用其remA方法。

<blockquote>
小技巧：平时看源码的时候，如果对某一段代码不甚理解，可以采用如下两个方法辅助：

+ 想象一个应用场景，使用这组类（或函数）写些测试用例。

+ 不妨“刻意地暂时忘记改源码的实现，完全按照自己的思路实现同样功能，只需要写出“大概伪码思路”即可，然后，两相对比，通常就比较明了作者的设计思路了。
</blockquote>

### 实现方式二

```

class PizzaD { 

	private List<PizzaMaterial> materials = new LinkedList<>();
	
	public PizzaD() {
	    materials.add(new Crust());
	}

	public PizzaD addMaterial(PizzaMaterial material) {
        materials.add(material);
	}
	
    public PizzaD remA(PizzaMaterial material) {
    	// 操作链表
    }

    public PizzaD topAwC() {
       // 操作链表
    }

    public PizzaD subAbC() {
       // 操作链表
    }
}

abstract class PizzaMaterial {
	// ...
}

class Crust extends PizzaMaterial { 
    // ...
}

// 下面是各种顶料
class Cheese { 
    PizzaD p;
    Cheese (PizzaD _p) {
        p = _p;
    }
    
}

class Olive extends PizzaD { 
    PizzaD p;
    Olive (PizzaD _p) {
        p = _p;
    }
    
}

class Anchovy extends PizzaD { 
    PizzaD p;
    Anchovy (PizzaD _p) {
        p = _p;
    }
    
}

class Sausage extends PizzaD { 
    PizzaD p;
    Sausage (PizzaD _p) {
        p = _p;
    }
    
}
```

用例：

```
public static void main(String[] args) {
    PizzaD p = new PizzaD();
    
    p.addMaterial(new Cheese());
    p.addMaterial(new Anchovy());
    p.addMaterial(new Olive());
    p.addMaterial(new Sausage());
    
    p.remA();
    p.topAwC();
    p.subAbC();
}
```

### 对比

+ 方式一将**Pizza实体**、**面皮**、**顶料**均抽象为“PizzaD”；方式二中将**Pizza实体**抽象为“PizzaD”，而将面皮和顶料抽象为“PizzaMaterial”。

+ 方式一通过“串串”的形式组合`构造函数`，构造**Pizza实体*；方式二中通过**Pizza实体**中的`addMaterial()`方法，构造**Pizza实体**。

+ 方式一更函数化，方式二更像通常的“面向对象”。
