---
author: "patrick.unicorn"
output:
  html_document:
    css: ../../css/main.css
    highlight: null
    theme: null
---

读《Java Performance: The Definitive Guide》

* * *

## 基本概念

+ JVM 性能调优的过程实际上与 C++ 程序员在编译时通过测试选择编译参数，以及 PHP 码农在 php.ini
文件中选择适当变量等过程非常类似。

+ 编码和调优常常被认为是两个不同的专业领域：性能调优工程师只是竭力将 JVM的性能发挥到极致，而开发人员只关心他们的代码逻辑是否正确。这种区分没有什么意义。任何从事Java相关工作的人都应该熟谙代码在 JVM 中的行为，以及如何调优才能提升性能。

+ 商业版 JVM 中和性能密切相关的一个特性就是 Java 飞行记录器（Java Flight Recorder，JFR）。

+ 除了少数例外，JVM 主要接受两类标志：布尔标志和附带参数的标志。

+ 布尔标志采用以下语法： -XX:+FlagName 表示开启， -XX:-FlagName 表示关闭。

+ 附带参数的标志采用以下语法： -XX:FlagName=something ，表示将标志 flagName 的值设置为 something 。其中 something 通常可以为任意值。例如 -XX:NewRatio=N ，表示 NewRatio可以设置为任意值 N。

+ 在给定的命令行上，添加 -XX:+Printflagsfinal （默认为 false ，即“关闭” ）就能获得具体运行环境中特定标志的默认值。

+ 需要更高性能时，算法是否优秀就是重中之重了。

+ 要创建和销毁的对象越多，垃圾收集的工作量就越大；要分配和持有的对象越多，GC 的周期就越长；要从磁盘装载进 JVM 的类越
多，程序启动所花费的时间就越长；要执行的代码越多，机器硬件缓存的效率就越低；而执行的代码越多，花费的时间就越长。

+ 随着新特性的添加和新要求的采纳（为了与对手竞争） ，程序会越来越大，越来越慢。

+ “我们不应该把大量时间都耗费在那些小的性能改进上；过早考虑优化是所有噩梦的根源” 。这句名言的重点是，最终你应该编写清晰、直接、易读和易理解的代码。这里的“优化”应该理解为虽然算法和设计改变了复杂程序的结构，但是提供了更好的性能。那些真正的优化最好留到以后，等到性能分析表明这些措施有巨大收益的时候才进行。而这里所指的过早优化，并不包括避免那些已经知道对性能不好的代码结构。每行代码，如果有两种简单、直接的编程方式，那就应该选择性能更好的那种。

+ 常用的打印日志中，如果有拼接字符串的消息，应该首先判断日志是否开启，以避免不必要的字符串连接开销，比如：

```
// 不好
log.log(Level.FINE, "I am here, and the value of X is" 
    + calcX() + " and Y is " + calcY());
    
// 优化
if (log.isLoggable(Level.FINE)) {
    log.log(Level.FINE,
        "I am here, and the value of X is {} and Y is {}",
        new Object[]{calcX(), calcY()});
}
```

+ 在分布式环境中，比如 Java EE 应用服务器、负载均衡器、数据库和后台企业信息系统，Java 应用服务
器的性能问题可能只是其中很小的部分。

+ 对于整体系统，我们需要采取结构化方法针对系统的所有方面分析性能。CPU使用率、I/O延迟、系统整体的吞吐量都必须测量和分析。只有到那时，我们才能判定到底是哪个组件导致了性能瓶颈。

+ 增加系统某个组件的负载从而导致整个系统性能变慢，这项原则不仅限于数据库。CPU密集型的应用服务器增加负载，或者越来越多线程试图获取已经有线程等待的锁，还有许多其他场景，也都适用这项原则。

+ 优化的原则：

<blockquote>
+ 借助性能分析来优化代码，重点关注性能分析中最耗时的操作。然而请注意，这并不意
味着只看性能分析中的叶子方法 。

+ 利用奥卡姆剃刀原则诊断性能问题。性能问题最可能的原因应该是最容易解释的：新代
码比机器配置更可能引入性能问题，而机器配置比 JVM 或者操作系统的 bug 更容易引
入性能问题。隐藏的 bug 确实存在，但不应该把最可能引起性能问题的原因首先归咎于
它，而只在测试用例通过某种方式触发了隐藏的 bug 时才关注。但不应该一上来就跳到
这种不太可能的场景。

+ 为应用中最常用的操作编写简单算法。以估算数学公式的程序为例，用户可以决定他所
期望的最大容许误差为 10% 或 1%。如果 10% 的误差适合多数用户，那么优化代码就
意味着即便误差范围缩小为 1%，但是速度变慢了
</blockquote>

+ **微基准测试**用来测量微小代码单元的性能，包括调用同步方法的用时与非同步方法的用时比较，创建线程的代价与使用线程池的代价，执行某种算法的耗时与其替代实现的耗时，等等。相当于测试函数或代码片段。

+ 编写多线程微基准测试时务必深思熟虑。当若干个线程同时执行小段代码时，极有可能会产生同步瓶颈（以及其他线程问题） 。所以，如果我们过多依赖多线程基准测试的结果，就常常会将大量时间花费在优化那些真实场景中很少出现的同步瓶颈上，而不是性能需求更迫切的地方。

+ 考虑这样的微基准测试，即有两个线程同时调用同步方法。由于基准测试的代码量相对于被测方法来说比较少，所以多数时间都是在执行同步方法。假设执行同步方法的时间只占整个微基准测试的 50%，即便少到只有两个线程，同时执行同步代码的概率仍然很高。因此基准测试运行得很慢，并且随着线程数的增加，竞争所导致的性能问题将愈演愈烈。最终结果就是，测试衡量的是 JVM 如何处理竞争，而不是微基准测试的本来目的。

+ 微基准测试中的输入值必须事先计算好，不能使用随机数生成函数放在测试代码中，因为，随机生成函数也要耗费时间。

+ 我们应该为常见的场景进行优化，即使需要加入特殊的处理逻辑。

+ Java 的一个特点就是代码执行的越多性能越好，基于这点，微基准测试应该包括热身期，使得编译器能生成优化的代码。

+ 在做回归测试的时候，追踪级别设为纳秒很有意义。如果集合操作每次都节约几纳秒，日积月累下来意义就很重大了。对于那些不频繁的操作来说，例如那种同时只需处理一个请求的 servlet，修复微基
准测试所发现的纳秒级性能衰减就是浪费时间，这些时间用在优化其他操作上可能会更有价值。微基准测试难于编写，真正管用的又很有限。所以，应该了解这些相关的隐患后再做出决定，是微基准测试合情合理值得做，还是关注宏观的测试更好。

+ 衡量应用性能最好的事物就是应用自身，以及它所用到的外部资源。如果正常情况下应用需要调用 LDAP 来检验用户凭证，那应用就应该在这种模式下测试。虽然删空 LDAP 调用在模块测试中有一定意义，但应用本身必须在完整真实配置的环境中测试。

+ 任何应用（包含独立运行的 JVM）都可以像这样划分成一系列步骤，方框中的模块、子系统等产生数据的速度取决于它们的效率。（耗费的时间包括子系统代码的执行时间，也包括网络传输的时间、磁盘传输的时间，等等。如果是模块化的模型，时间应该只包括该模块内代码的执行时间。）数据进入子系统的速率取决于前一个模块或系统的输出速率。

+ 全应用测试有个很重要的场景，就是同一台机器上同时运行多个应用。许多 JVM 的默认调优都是默认假定整个机器的资源都归 JVM 使用。如果单独测试，优化效果很好。如果在其他应用（包括但不限于 Java 程序）运行的时候进行测试，性能会有很大的不同。

+ 单个 JVM（默认配置）执行 GC 周期时，该机器上所有处理器的 CPU 使用率都会变成 100%。如果测量程序执行时的平均CPU 使用率，大概会有 40%——实际意思是，某些时候 30%的CPU被占用，其他时候为100%。当隔离 JVM 时，它可以运行得很好，但如果 JVM 与其他应用并发运行，它就不可能在 GC 时获得 100% 的CPU。此时测出来的性能会与它单独运行时不同。这是微基准测试和模块测试不可能让你全面了解应用性能的另一个原因。

+ 不进行整体应用的测试，就不可能知道哪部分的优化会产生回报。

+ 使 Java 代码更快的常用方法是更好的算法，这不依赖Java 调优或者 Java 编码实践。

+ 虚拟机会花几分钟（或更长时间）全面优化代码并以最高性能执行。由于这个（以及其他）原因，研究Java的性能优化就要密切注意代码优化的热身期：大多数时候，应该在运行代码执行足够长时间，已经编译并优化之后再测量性能。

+ 许多情况下应用从开始到结束的整体性能更为重要。报告生成器处理 10 000 个数据元素需要花费大量时间，但对最终用户而言，处理前 5000个元素是否比后5000个慢50%并不重要。即便是像应用服务器这样的系统——其性能必定会随运行时间而改善——初始的性能依然很重要。某种配置下的应用服务器需要 45 分钟才能达到性能峰值。

+ 在客户端 - 服务器的吞吐量测试中，并不考虑客户端的思考时间。客户端向服务器发送请求，当它收到响应时，立刻发送新的请求。持续这样的过程，等到测试结束时，客户端会报告它所完成的操作总量。客户端常常有多个线处理，所以吞吐量就是所有客户端所完成的操作总量。通常这个数字就是每秒完成的操作量，而不是测量期间的总操作量。这个指标常常被称作每秒事务数（TPS） 、每秒请求数（RPS）或每秒操作次数（OPS） 。

+ 响应时间测试和吞吐量测试（假设后者是基于客户端 - 服务器模式）之间的差别是，响应时间测试中的客户端线程会在操作之间休眠一段时间。这被称为思考时间。响应时间测试是尽量模拟用户行为：用户在浏览器输入URL，用一些时间阅读返回的网页，然后点击页面上的链接，花一些时间阅读返回的网页，等等。当测试中引入思考时间时，吞吐量就固定了：指定数量的客户端，在给定思考时间下总是得到相同的 TPS（少许差别，参见框注） 。基于这点，测量请求的响应时间就变得重要了：服务器的效率取决于它响应固定负载有多快。

+ 性能测试的结果会随时间而变。即便程序每次处理的数据集都相同，产生的结果也仍然会有差别。因为有很多因素会影响程序的运行，如机器上的后台进程，网络时不时的拥堵等。好的基准测试不会每次都处理相同的数据集，而是会在测试中制造一些随机行为以模拟真实的世界。这就会带来一个问题：运行结果之间的差别，到底是因为性能有变化，还是因为测试的随机性。可用以下方法来解决这个问题，即多次运行测试，然后对结果求平均。当被测代码发生变化时，就再多次运行测试，对结果求平均，然后比较两个平均值。

+ 比较基准测试的结果时，我们不可能知道平均值的差异是真的性能有差还是随机涨落。最好的办法是先假设“平均值是一样的” ，然后确定该命题为真时的几率。如果命题很大几率为假，我们就有信心认为平均值是真的有差别（虽然我们永远无法 100% 肯定） 。注：《测试技术计量》课程，有一些对实验结果进行比对的方法。

+ 因代码更改而进行的测试称为回归测试。在回归测试中，原先的代码称为基线（baseline） ，而新的代码称为试样（specimen） 。

+ 所有的客户端 - 服务器测试都存在风险，即客户端不能足够快地向服务器发送数据。这可能是由于客户端机器的 CPU 不足以支持所需数量的客户端线程，也可能是因为客户端需要花大量时间处理响应才能发送新的请求。在这些场景中，测试衡量的其实是客户端性能而不是服务器性能的。其中的风险依赖于每个线程所承载的工作量（客户端机器的线程数和配置） 。由于客户端线程需要执行大量工作，零思考时间（面向吞吐量）测试更可能会遇到这种情形。因此，通常吞吐量测试比响应时间测试的线程数少，线程负载也小。通常吞吐量测试也会报告请求的平均响应时间。但平均响应时间的变化并不表示性能有问题，除非报告的吞吐量相同。能够承受 500 OPS、响应时间 0.5 秒的服务器，它的性能要好过响应时间 0.3 秒但只有 400 OPS 的服务器。吞吐量测试总是在合适的热身期之后进行。

+ 衡量响应时间有两种方法。响应时间可以报告为平均值：请求时间的总和除以请求数。响应时间也可以报告为百分位请求，例如第 90 百分位响应时间。如果 90% 的请求响应小于1.5 秒，且 10% 的请求响应不小于 1.5 秒，则 1.5 秒就是第 90 百分位响应时间。两种方法的一个区别在于，平均值会受离群值影响。这是因为计算平均值时包括了离群值。离群值越大，对平均响应时间的影响就会越大。对于Java应用来说，由于GC的存在，更容易引起这样的离群值。因此，一般最好同时考虑**平均响应时间**和至少一种**百分位响应时间**。

+  Faban（http://faban.org/）为例，这是一个开源的、基于 Java 的负载生成器。

+ 查找代码性能变化的正确方法是先决定一个显著性水平——比如 0.1——然后用 t 检验判定在这个显著性水平上试样是否与基线有差别。

```
统计学中的显著性与重要性

显著性差异并不意味着统计结果对我们更重要。平均为 1 秒的变化很小的基线，和平均为 1.01 秒的变化很小的试样，其 p 值可能为 0.01：结果的差别有 99% 的置信度。
但结果的差别只有 1%。现在假定另外一个测试，试样和基线有 10% 的变动，但是 p值为 0.2，即非统计显著。哪个测试的结果最为重要？这需要更多时间来审查。审查后发现虽然相差 10% 的测试的置信度低，但在用时上更加优化（如果可能的话，可以用更多数据来验证测试结果是否真的统计显著） 。仅仅因为 1% 差异的可能性更大，并不意味着它更重要。
```

+  Apache Commons Mathematics 类库中的 TTest 可以计算统计结果的**置信度**。

+ 程序时不时会表现出随机行为，而一旦引入了随机性，我们就再也无法 100% 确定这些数据意味着什么了。使用统计分析有助于使结果变得更客观，但即便如此，仍然免不了主观臆断。理解这些数据背后的概率及其意义，有助于降低主观性。

## 性能调优工具

+ 通常 CPU 使用率可以分为两类：用户态时间和系统态时间（Windows 上被称作 privileged time） 。用户态时间是 CPU 执行应用代码所占时间的百分比，而系统态时间则是 CPU 执行内核代码所占时间的百分比。系统态时间与应用相关，比如应用执行 I/O 操作，系统就会执行内核代码从磁盘读取文件，或者将缓冲数据发送到网络，等等。任何使用底层系统资源的操作，都会导致应用占用更多的系统态时间。性能调优的目的是，在尽可能短的时间内让 CPU 使用率尽可能地高。

+ CPU 使用率是一段时间内的平均数——5 秒、30 秒，也可能只有 1秒那么短（不过永远不会比这还要短） 。比如，10 分钟内一个程序执行的 CPU 使用率为50%。如果代码调优之后，CPU 使用率达到了 100%，说明程序的性能翻了倍：程序只需要执行 5 分钟就可以了。如果性能再翻倍，CPU 仍将是 100%，而执行完程序只要 2.5 分钟。CPU 使用率表示程序以多高的效率使用 CPU，所以数字越大，性能越好。

+ Linux查看CPU情况的工具是：**vmstat**。

+ 提高 CPU 使用率，一直都是批处理任务的目的。如果 CPU已经达到 100%，你仍然可以寻找优化，使得工作完成的更快（也要尽量保持 100%CPU 使
用率） 。

+ 一般来说，多 CPU 多线程的目的仍然是通过不阻塞线程来提高 CPU 使用率，或者是在线程完成工作等待更多任务时降低 CPU 使用率。

+ 在多线程多 CPU 下，需要重点考虑以下 CPU 空闲的情形：即便有事可做，CPU 仍然空闲。这在程序没有更多线程可用的时候可能会出现。典型的情况是，应用以固定尺寸
的线程池运行各种任务。每个线程同时只能执行一个任务，当线程被某个任务阻塞时（例如，等待数据库的响应） ，它就没法捡出新任务执行了。所以此时的情况就是，有任务需要执行（有事可做） ，却没有线程执行它们，结果就是 CPU 处在空闲时间。

+ Windows 和 Unix 系统都可以监控可运行（意味着没有被 I/O 阻塞、休眠等）的线程数。Unix 系统称之为运行队列（run queue） ，vmstat输出中就有。Windows 将这个数字称为处理器队列（processor quque），使用typeperf查看。但是需要注意：Unix 系统的运行队列长度（ vmstat 输出）是所有正在运行或待运行（即一旦有可用 CPU就可以运行）的线程数。而在 Windows 中，处理器队列长度就不包括正在运行的线程。

+ 如果试图运行的线程数超过了可用的 CPU，性能就会下降。一般来说，Windows 的处理器队列长度最好为 0，小于或等于 Unix 系统 CPU 的数目。如果在相当长时间内运行队列很长，说明系统已经过载，这时你应该检查系统，减少机器正在处理的工作量（将工作转移到其他机器或者优化代码） 。

+ 检查应用性能时，首先应该审查 CPU 时间。优化代码的目的是提升而不是降低（更短时间段内的）CPU 使用率。在试图深入优化应用前，应该先弄清楚为何 CPU 使用率低。

+ 监控磁盘使用率有两个目的。第一个目的与应用本身有关：如果应用正在做大量的磁盘I/O 操作，那 I/O 就很容易成为瓶颈。想了解何时磁盘 I/O 是瓶颈非常困难，因为这取决于应用的行为。

+ Linux系统使用**iostat**查看磁盘情况。

+ Linux 中可以查看进程的 47.89%的事件在 iowait （表示正在等待磁盘） ，这时表示磁盘速度赶不上IO请求了。

+ 监控磁盘使用率的第二个理由是——即便预计应用不会有很高的 I/O——有助于监控系统是否在进行内存交换。正在内存交换的系统——从主内存移动数据到磁盘或者反过来——一般来说，性能比较差。还有其他系统工具可以报告系统交换，例如 vmstat 输出中有两列（ si 是换进， so 是换出）可以警告我们系统是否正在交换。

+ 写入磁盘的应用遇到瓶颈，是因为写入数据的效率不高（吞吐量太低） ，或者是因为写入太多数据（吞吐量太高） 。

+ 网络使用率类似磁盘流量：应用可能没有充分利用网络所以带宽很低，或者写入某网络接口的总数据量超过了它所能处理的量。

+ 由于标准的系统工具通常只能显示某个网络接口发送和接收的数据报数和字节数，所以它们在监控网络流量方面差强人意。虽然这些信息有用，但无法告诉我们网络是没有充分利用，还是过度使用。

+ Unix 系统监控网络的基本工具是 netstat （大多数 Linux 发行版中还没有包括 netstat ，必须单独获得） 。Windows 上则可以在脚本中使用 typeperf ，监控网络使用率.

+ 有许多开源和商业工具可以监控网络带宽。Unix 里一个受欢迎的命令行工具就是 nicstat ，它可以显示每个网络接口的流量概要，包括网络接口的使用度。

+ typeperf 或 netstat 这样的工具可以报告读取和写入的数据，但是要计算网络使用率，你必须自己用脚本计算接口的带宽。虽然一般工具报告的单位是字节 / 秒（Bps） ，但请切记，带宽的单位是位 / 秒（bps） 。1000 兆位网络每秒处理 125 兆字节（MB） 。

+ 网络无法支持 100% 的使用率。对本地以太局域网来说，承受的网络使用率超过 40% 就意味着接口饱和了。如果网络是包交换或使用不同的传输介质，网络使用率的最大值就可能会不同，因此最好是评估网络架构之后再确定合适的值。这个值与 Java 无关，只是简单利用网络参数和操作系统接口。

+ 对基于网络的应用来说，务必要监控网络以确保它不是瓶颈。

+ `jcmd <process id> <command>` 用来打印Java进程的所涉及的基本类、线程和VM信息。

+ jconsole提供JVM活动的GUI视图。

+ jhat用于读取内存堆dump文件，用于分析。

+ jmap用于内存堆或其他JVM内存信息的dump。

+ jinfo查看JVM的系统属性，可以动态设置一些系统属性。

+ jstack转储Java进程中的线程栈信息，可以用于分析死锁的等。

+ jstat提供GC和类装载的信息。

+ jvm的GUI工具，可以用来剖析应用中的应用，也可以用来分析内存堆dump文件。

+ `jcmd process_id VM.uptime`或`jinfo -sysprops process_id`查看JVM运行多长时间了。

+ jconsole 的“VM 摘要”页可以显示程序所用的命令行，或者用 jcmd 显示`jcmd process_id VM.command_line`。

+ `jcmd process_id VM.flags [-all]`可以查看JVM的所有设置属性信息。类似与Gradle的`gradle properties`。

+ 诊断性能问题时，找出哪些标志起作用是很常见的事。JVM 运行时，可以用 jcmd 做到这一点。如果想找出特定 JVM 的平台特定的默认值是什么，那么在命令行上添加 -XX:+Printflagsfinal 会很有用：`java other_options -XX:+PrintFlagsFinal -version`，其与上面一项中的jcmd命令输出结果一样。

```
输出结果：uintx InitialHeapSize := 4169431040 {product / pd product / manageable /  C2 diagnostic}

1. 冒号表示标志使用的是非认值
2. product 表示在所有平台上的默认设置都是一致的。 
3. pd product 表示标志的默认值是独立于平台的。
4. manageable 表示运行时可以动态更改标志的值。
5. C2 diagnostic表示为编译器工程师提供诊断输出，帮助理解编译器正以什么方式运作
```

+ 另一种查看运行中的应用的此类信息的工具，叫作 jinfo 。 jinfo 的好处在于，它允许程序在执行时更改某个标志的值，并且可以单独检查输出单个标志的值。

```
jinfo 可以更改任意标志的值，但并不意味着 JVM 会响应更改。比如说，大多数影响 GC 算法行为的标志都在启动时使用，以决定垃圾收集器的行为方式。之后通过 jinfo 更改标志值，并不会导致 JVM 改变它的行为。它会以初始时的算法继续执行。所以这个技术只会对那些在 Printflagsfinal 输出中标记为 manageable 的标志有效
```

+ `jstack process_id`或者`jcmd process_id Thread.print`可以打印出每个线程的详细输出，对于分析线程阻塞、死锁等很有用。

+ jconsole 或 jstat 可以提供应用已使用类的个数。 jstat 还能提供类编译相关的信息。

+ 几乎所有的监控工具都能报告一些 GC 活动的信息。 jconsole 可以用实时图显示堆的使用情况。 jcmd 可以执行 GC 操作。 jmap 可以打印堆的概况、永久代信息或者创建堆转储。jstat 可以为垃圾收集器正在执行的操作生成许多视图。

+ jvisualvm 的 GUI 界面可以捕获堆转储，也可以用命令行 jcmd 或 jmap 生成。堆转储是堆使用情况的快照，可以用不同的工具进行分析，包括 jvisualvm 和 jhat，或者外部工具，如：Eclipse Memory Analyzer Tool等。

+ 几乎所有的 Java 性能分析工具都是用 Java 写的，并以“关联” （attaching）应用的方式进行性能分析——意思是性能分析器开启与目标应用之间的 socket（或其他通信通道） 。随后目标应用和性能分析工具交换应用的行为信息。

+ 性能分析有两种模式：数据采样或数据探查。数据采样是性能分析的基本模式，带来的开销最小，这点很重要。性能分析为人诟病的一点就是，对应用进行的测量会改变它的性能。 

+ 探查分析器相比于采样分析器，侵入性更强，但它们可以给出关于程序内部所发生的更有价值的信息。探查分析器会在类加载时更改类的字节码（即插入统计调用次数的代码
等） 。相比采样分析器，探查分析器更可能会将性能偏差引入应用。

+ 优先优化哪些调用次数更多的方法，会获得更大的性能提升。

+ 如果希望能看到那些阻塞调用所花费的时间，即线程在 wait() ——等待其他线程唤醒——中的用时决定了许多应用的整体执行时间。那么在大多数基于 Java 的性能分析器可以通过设置过滤器和调整其他选项来显示或隐藏这些阻塞方法。

+ Oracle Solaris Studio是一个非常有用的分析Linux的性能分析器。

+ 基于Java 的性能分析工具所不能提供的——应用花在 GC 上的时间。在基于 Java 的性能分析工具中，GC 线程的影响几乎看不到。 （除非测试所运行的机器是 CPU 受限，否则编译器线程占用大量时间并无大碍：虽然编译线程会消耗大量的 CPU 时间，但只要机器上有更多可用的 CPU，应用自身就不受影响，因为编译是在后台发生。 ）因此，可以考虑使用Oracle Solaris Studio等c/c++性能分析器。

+ 性能分析器是查找性能瓶颈最重要的工具，但你必须学会如何使用它们，然后找到需要优化的代码区域。

+ 商业版 Java 7（从 7u40 开始）和 Java 8 包含了称为 Java Mission Control（以下称 JMC）的监控新特性。该特性不开源，需要付费购买。

+ JMC 的关键特性是 Java 飞行记录器（Java Flight Recorder，JFR） 。正像它名字所暗示的，JFR 数据是 JVM 的历史事件，这些可以用来诊断 JVM 的历史性能和操作。JFR 的基本操作是开启一组事件（例如，线程等待某个锁而被阻塞的事件） 。每当选择的事件发生时，就会保存相应的数据（保存在内存或文件中） 。数据流保存在循环缓冲中，所以只有最近的事件。JMC 可以显示这些事件——实时从 JVM 获取或者从文件读取——你可以对这些事件进行分析，诊断性能问题。 JFR的详细使用，见书中。

## Java编译器优化

+ 大多数情况下,所谓编译器调优,其实就只是为目标机器上的 Java 选择正确的 JVM 和编 译器开关(-client、-server 或 -XX:+TieredCompilation)而已。分层编译通常是长期运 行应用的最佳选择,而对于运行时间短的应用来说,分层编译与 client 编译器的性能差别很小。

+ 确实没有什么好的机制可以算出程序所需要的代码缓存。所以,如何增加代码缓存,基本 上就是摸着石头过河,通常的做法是简单地增加 1 倍或 3 倍。-XX:ReservedCodeCacheSize=N(对特定编译器来说,N 为默认的值)标志可以设置代码缓存的最大值。代码缓存的管理和大多数 JVM 内存一样,有初始值(由 -XX:InitialCodeCacheSize=N指定)。代码缓存从初始大小开始分配,一旦充满就会增加(直至最大值)。

+ 理解 JVM 保留内存和分配内存方式之间的差别非常重要。这种差别在代码缓存、Java 堆以及其他 JVM 本地内存结构中都存在。

+ 代码缓存设为 1 GB,JVM 就会保留 1 GB 的本地内存空间。虽然这部分内存在需要时才会分配,但它仍然是被保留的。

+ 分层编译很容易达到代码缓存默认配置的上限(特别是在 Java 7 中)。使 用分层编译时,应该监控代码缓存,必要时应该增加它的大小。

+ 触发代码编译的条件。其中最主要的因素是代码执行的频度。一旦执行达到一定次数,且达到了编译阈值,编译器就可以获得足够的信息编译代码了。

+ 编译是基于两种 JVM 计数器的:方法调用计数器和方法中的循环回边计数器。回边实际上可看作是循环完成执行的次数,所谓循环完成执行,包括达到循环自身的末尾,也包括 执行了像 continue 这样的分支语句。

+ JVM 执行某个 Java 方法时,会检查该方法的两种计数器总数,然后判定该方法是否适合编译。如果适合,该方法就进入编译队列。这种编译没有正式的名称,通常叫标准编译。

+ 如果循环真的很长——或因包含所有程序逻辑而永远不退出,又该如何?在这种情 况下,JVM不等方法被调用就会编译循环。所以循环每完成一轮,回边计数器就会增加并被检测。如果循环的回边计数器超过阈值,那这个循环(不是整个方法)就可以被编译。由于仅仅编译循环还不够,JVM必须在循环进行的时候还能编译循环。在循环代码编译结束后,JVM 就会替换还在栈上的代码,循环的下一次迭代就会执行快得多的编译代码。故而称为栈上替换(On-Stack Replacement,OSR)。

+ 标准编译由 -XX:CompileThreshold=N 标志触发。使用 client 编译器时,N 的默认值是 1500, 使用 server 编译器时为 10 000。更改 CompileThreshold 标志的值,将使编译器提早(或延 后)编译。然而请注意,尽管有一个标志,但这个标志的阈值等于回边计数器加上方法调 用计数器的总和。

+ 更改 OSR 编译阈值的情况非常罕见。事实上,虽然 OSR 编译在基准测试(特别是微基准测试)中经常发生,但在实际运行时并不经常出现。

+ VM 供应商提交的基准测试已经验证过上述调优,不同设置的基准测试间并没有什么性能差异。他们使用较低的设置主要基于以下两个原因:
    1. 节约一点应用热身的时间;
    2. 使得某些原本可能不会被 server 编译器编译的方法得以编译。
    
<blockquote>
每种计数器的值都会周期性减少(特别是当 JVM 达到安全点时)。

实际上,计数器只是方法或循环最新热度的度量。由此带来的一个副作用是,
执行不太频繁的代码可能永远不会编译,即便是永远运行的程序(相对于热来说,有时称这些方法为温热 [lukewarm])。
这就是通过减少编译阈值来进行优化的一种情况,它也是分层编译通常比单独的 server 编译器 要快的原因之一。
</blockquote>

+ 如果开启 PrintCompilation,每次编译一个方法(或循环)时,JVM 就会打印一行被编译 的内容信息。输出的信息在不同的 Java 发布版之间会有所不同，绝大多数编译日志的行具有以下格式: 

```
timestamp compilation_id attributes (tiered_level) method_name size deopt 

此处的时间戳 timestamp 是编译完成的时间(相对于 JVM 开始的时间 0)。

compilation_id 是内部的任务 ID。通常这个数字只是简单地单调增长,不过在使用 server编译器时(或者某个时刻编译器的线程数增加时),你有时会发现乱序的compilation_id。


attributes 是一组 5 个字符长的串,表示代码编译的状态。
5字符属性串可以同时出现 2 个或多个字符。不同的属性如下所列: 

• %:编译为 OSR。
• s:方法是同步的。
• !:方法有异常处理器。
• b:阻塞模式时发生的编译。
• n:为封装本地方法所发生的编译。

n 属性表明 JVM 生成了一些编 译代码以便于调用本地方法。
size是编译后代码的大小(单位是字节)。这是 Java 字节码的大小,不是被编译代码的大小.
```

+ jstat 有两个有关编译器信息的标志。jstat -compiler 标志提供了关于多少方法被编译的概
要信息;可以用 jstat -printcompilation 标志获取最近被编译的方法。jstat 借助一个可选 参数反复执行操作,你可以看到随时间变化有哪些方法被编译了。

+ 书中的《高级编译器调优》一节主要是针对JVM工程师调优JVM的，一般开发者不必须理解。

+ PrintCompilation 标志输出的讨论中曾提到两种代码逆优化的情况。逆优化意味着编译器 不得不“撤销”之前的某些编译;结果是应用的性能降低，有两种逆优化的情形:代码状态分别为“made not entrant”(代码被丢弃)和“made zombie”(产生僵尸代码)时。

+ 大概来说，在分层编译中,代码先由 client 编译器编译,然 后由 server 编译器编译。

+ 一般来说,像僵尸代码重编译 这样小的操作对大多数应用都不会有显著的影响。

### Java垃圾收集

+ 垃圾收集由两步构成:查找不再使用的对象,以及释放这些对象所管理的内存。

+ 垃圾收集的性能就是由这些基本操作所决定的: 找到不再使用的对象、回收它们使用的内存、对堆的内存布局进行压缩整理。

+ 垃圾收集器回收对象,或者在内存中移动对象时,必须确 保应用程序线程不再继续使用这些对象。这一点在收集器移动对象时尤其重要:在操作过 程中,对象的内存地址会发生变化,因此这个过程中任何应用线程都不应再访问该对象。所有应用线程都停止运行所产生的停顿被称为时空停顿(stop-the-world)。通常这些停顿对 应用的性能影响最大,调优垃圾收集时,尽量减少这种停顿是最为关键的考量因素。

+ 所有的垃圾收集器都遵循了同一个方式,即根据情况将 堆划分成不同的代(Generation)。这些代被称为“老年代”(Old Generation 或 Tenured Generation)和“新生代”(Young Generation)。新生代又被进一步地划分为不同的区段, 分别称为 Eden 空间和 Survivor 空间(不过 Eden 有时会被错误地用于指代整个新生代)。

+ 采用分代机制的原因是很多对象的生存时间非常短。

+ 对象首先在新生 代中分配。新生代填满时,垃圾收集器会暂停所有的应用线程,回收新生代空间。不再使用 的对象会被回收,仍然在使用的对象会被移动到其他地方。这种操作被称为 Minor GC。采用这种设计有两个性能上的优势。其一,由于新生代仅是堆的一部分,与处理整个堆相 比,处理新生代的速度更快。第二个优势源于新生代中对象分配的方式。对象分配于 Eden 空间(占据了新生代空间的 绝大多数)。垃圾收集时,新生代空间被清空,Eden 空间中的对象要么被移走,要么被回 收;所有的存活对象要么被移动到另一个 Survivor 空间,要么被移动到老年代。由于所有 的对象都被移走,相当于新生代空间在垃圾收集时自动地进行了一次压缩整理。

+ 所有的垃圾收集算法在对新生代进行垃圾回收时都存在“时空停顿”现象。

+ 对象不断地被移动到老年代,最终老年代也会被填满,JVM 需要找出老年代中不再使用 的对象,并对它们进行回收。而这便是垃圾收集算法差异最大的地方。简单的垃圾收集算法直接停掉所有的应用线程,找出不再使用的对象,对其进行回收,接着对堆空间进行整 理。这个过程被称为 Full GC,通常导致应用程序线程长时间的停顿。

+ 有可能在应用线程运行的同时找出不再使用的对象;CMS 和 G1 收集器就是通过这种方式进行垃圾收集的。由于它们不需要停止应用线程 就能找出不再用的对象,CMS 和 G1 收集器被称为 Concurrent 垃圾收集器。同时,由于它 们将停止应用程序的可能降到了最小,也被称为低停顿(Low-Pause)收集器(有时也称 为无停顿收集器,虽然这个叫法相当不确切)。Concurrent收集器也使用各种不同的方法对老年代空间进行压缩。
使用 CMS 或 G1 收集器时,应用程序经历的停顿会更少(也更短)。其代价是应用程序会消耗更多的CPU。CMS 和 G1 收集也可能遭遇长时间的 Full GC 停顿(尽量避免发生那样 的停顿是这些调优算法要考虑的重要方面)。

+ 评估垃圾收集器时,想想你需要达到的整体性能目标。每一个决定都需要权衡取舍。如果 应用对单个请求的响应时间有要求(譬如 Java 企业版服务器),你应该考虑下面这些因素。
• 单个请求会受停顿时间的影响——不过其受 Full GC 长时间停顿的影响更大。如果目标 是要尽可能地缩短响应时间,那么选择使用 Concurrent 收集器更合适。
• 如果平均响应时间比最大响应时间更重要(譬如 90% 的响应时间),采用 Throughput 收 集器通常就能满足要求。
• 使用 Concurrent 收集器来避免长的停顿时间也有其代价,这会消耗额外的 CPU。

+ 为批量应用选择垃圾收集器可以遵循下面的原则。
• 如果 CPU 足够强劲,使用 Concurrent 收集器避免发生 Full GC 停顿可以让任务运行得 更快。
• 如果 CPU 有限,那么 Concurrent 收集器额外的 CPU 消耗会让批量任务消耗更多的时间。

+ JVM 提供了以下 4 种不同的垃圾收集算法：Serial垃圾收集器，Throughput垃圾收集器，CMS收集器，G1垃圾收集器。

+ Serial 垃圾收集器是四种垃圾收集器中最简单的一种。如果应用运行在 Client 型虚拟机 (Windows 平台上的 32 位 JVM 或者是运行在单处理器机器上的 JVM)上,这也是默认的
垃圾收集器。
Serial 收集器使用单线程清理堆的内容。使用 Serial 收集器,无论是进行 Minor GC 还是 Full GC,清理堆空间时,所有的应用线程都会被暂停。进行 Full GC 时,它还会对老年代 空间的对象进行压缩整理。通过 -XX:+UseSerialGC 标志可以启用 Serial 收集器。

+ Throughput 收集器是 Server 级虚拟机(多 CPU 的 Unix 机器以及任何 64 位虚拟机)的默 认收集器。
Throughput 收集器使用多线程回收新生代空间,Minor GC 的速度比使用 Serial 收集器快 得多。处理老年代时 Throughput 收集器也能使用多线程方式。这已经是 JDK 7u4 及之后 的版本的默认行为,对于之前老版本的 JDK 7 虚拟机,通过 -XX:+UseParallelOldGC 标 志可以开启这个功能。由于 Throughput 收集器使用多线程,Throughput 收集器也常常 被称为 Parallel 收集器。Throughput 收集器在 Minor GC 和 Full GC 时会暂停所有的应 用线程,同时在 Full GC 过程中会对老年代空间进行压缩整理。由于在大多数适用的场 景,它已经是默认的收集器,所以你基本上不需要显式地启用它。如果需要,可以使用 -XX:+UseParallelGC、-XX:+UseParallelOldGC 标志启用 Throughput 收集器。

+ CMS 收集器设计的初衷是为了消除 Throughput 收集器和 Serial 收集器 Full GC 周期中 的长时间停顿。CMS 收集器在 Minor GC 时会暂停所有的应用线程,并以多线程的方式 进行垃圾回收。然而,这其中最显著的不同是,CMS 不再使用 Throughput 的收集算法(-XX:+UseParallelGC),改用新的算法来收集新生代对象(使用 -XX:+UseParNewGC 标志)。

+ CMS 收集器在 Full GC 时不再暂停应用线程,而是使用若干个后台线程定期地对老年代空 间进行扫描,及时回收其中不再使用的对象。这种算法帮助 CMS 成为一个低延迟的收集 器:应用线程只在 Minor GC 以及后台线程扫描老年代时发生极其短暂的停顿。应用程序 线程停顿的总时长与使用 Throughput 收集器比起来短得多。
这里额外付出的代价是更高的 CPU 使用:必须有足够的 CPU 资源用于运行后台的垃圾收 集线程,在应用程序线程运行的同时扫描堆的使用情况。除此之外,后台线程不再进行任 何压缩整理的工作,这意味着堆会逐渐变得碎片化。如果 CMS 的后台线程无法获得完成 他们任务所需的 CPU 资源,或者如果堆变得过度碎片化以至于无法找到连续空间分配对 象,CMS 就蜕化到 Serial 收集器的行为:暂停所有应用线程,使用单线程回收、整理老年 代空间。这之后又恢复到并发运行,再次启动后台线程(直到下一次堆变得过度碎片化)。 通过 -XX:+UseConcMarkSweepGC、-XX:+UseParNewGC 标志(默认情况下,这两个标志都是禁 用的)可以启用 CMS 垃圾收集器。

+ G1 垃圾收集器(或者垃圾优先收集器)的设计初衷是为了尽量缩短处理超大堆(大于 4 GB)时产生的停顿。G1 收集器属于 Concurrent 收集器。 其处理新生代的方式和其他多线程收集算法类似。老年代的垃圾收集工作由后台线程完成,大多数的工 作不需要暂停应用线程。由于老年代被划分到不同的区域,G1 收集器通过将对象从一个 区域复制到另一个区域,完成对象的清理工作,这也意味着在正常的处理过程中,G1 收 集器实现了堆的压缩整理(至少是部分的整理)。因此,使用 G1 收集器的堆不大容易发生 碎片化——虽然这种问题无法避免。通过标志 -XX:+UseG1GC (默认值是关闭的)可以启动 G1 垃圾收集器。

+ G1 的设计理念使得它比 CMS 更不容易遭遇 Full GC。

+ Java 也提供了一种机制让应用程序强制进行 GC: 调用 System.gc() 方法。通常情况 下,试图通过调用这个方法显式触发 GC 都不是个好主意。调用这个方法会触发Full GC(即使 JVM 使用 CMS 或者 G1 垃圾收集器), 应用程序线程会因此而停顿相当长 的一段时间。调用这个方法也不会让应用程序更高效。

+ 在做性能监控或者基准测试时。运行少量的代码进行基准 测试时,为了更快地预热 JVM,在测量周期之前强制进行一次 GC 还是有意义的。类 似的情况还包括在进行堆分析时,通常在获取堆转储之前,强制进行一次 Full GC 是 一个不错的主意。虽然大多数抓取堆转储的方法都能进行 Full GC,也存在其他的方法 可以强制进行 Full GC:你可以通过执行 jcmd < 进程号 > GC.run,或者使用 jconsole 连接到 JVM 在内存面板上单击“进行 GC”按钮。

+ 如果你运行的程序调用的第三方代码中错误地调用了 System.gc() 方法,可以通过 JVM 参数 -XX:+DisableExplicitGC 显式地禁止这种类型的 GC;默认情况下该标志是关闭的。

+ GC 算法的选择一方面取决于应用程序的特征,另一方面取决于应用的性能目标。

+ Serial 收集器最适用于应用程序的内存使用少于 100 MB 的场景。

+ 对批量任务而言,Throughput 收集器所引入的停顿,尤其是 Full GC 的停顿是主要的顾虑。如果有额外的 CPU 处理能力(这很可能是个问题),那么对批处理程序使用 Concurrent 收集器将极大 地提升应用程序的性能。这里的关键在于我们能否提供足够的 CPU 给 Concurrent 收集器 的线程进行后台的处理工作。

+ 多个应用程序线程、多个后台 GC 线程运行于多 CPU 的 系统上。如果操作系统无法在同时运行所有应用程序线程和 GC 后台线程,那么对 CPU 的 竞争就会反映到应用程序线程的停顿上。

+ 只有一个 CPU 可用时,CPU 将一直处于忙碌状态,要么是运行应用程序线程,要么是运 行 GC 线程。这种情况下,CMS 额外的后台线程就变成了一种负担。因此，如果使用CMS和G1收集器，必须保证足够的CPU资源，否则反而会降低系统性能。

+ 存在空闲 CPU 周期时,Concurrent收集器（CMS或G1）的性能更好；否则，Concurrent收集器会急剧下降，低于Throughput收集器。

+ 如果你关 注的仅仅是平均响应时间,那么 Throughput 收集器和 Concurrent 收集器似乎差别不大,都 能满足你的要求,你可以进一步考察 CPU 的使用情况(这时 Throughput 收集器可能是更 优的选择)。如果你关注的是 90% 或者其他百分比的响应时间,那就只能通过性能测试来 了解,完成这些任务应用程序会进行多少次 Full GC,最后决定选择哪种收集器。通常CMS收集器在百分比（如99%，90%）上的响应时间值更优秀。

+ 通常情况下,Throughput 收集器的平均响应时间比 Concurrent 收集器要好,但是在 90% 响应时间或者 99% 响应时间这几项指标上, Concurrent收集器比Throughput收集器要好一些。

+ 使用 Throughput 收集器会超负荷地进行大量 Full GC 时,切换到 Concurrent 收集器通常能获得更低的响应时间。可以查看FullGC的频率和次数，以决定。

+ 一般情况下,堆空间小于 4 GB时,CMS 收集器的性能比 G1 收集器好。CMS 收集器使用的算法比 G1 更简单,因此在比较简单的环境中(譬如堆的容量很小的情况),它运行得更快。使用大型堆或巨型堆时, 由于 G1 收集器可以分割工作,通常它比 CMS 收集器表现更好。因此，对于现代大多数的应用服务器（通常堆空间均大于8G）来说，G1的表现要好于CMS。

+ 由于 CMS 收集器不对堆进行压缩整理(除非发生了耗时的 Full GC),堆的碎片化也会触 发 CMS 收集器进行 Full GC。G1 算法在处理过程中随时进行着堆的压缩整理,不过 G1 收 集器依然可能遭遇堆的碎片化问题,但是与 CMS 收集器比较起来,它的设计让它又领先 了一步。

+ 在这三种收集器（Throughput、CMS、G1）的选择时还有一些微妙的无形因素需要考虑。Throughput 收集器是 这三个收集器中年代最久远的一个,这意味着 JVM 工程师们已经花费了大量的时间精力 雕琢把玩它,它的习性也更为大家所熟知。G1 作为相对较新的一种垃圾收集算法,更容 易碰到设计时无法预期的极端情况。相对而言,G1 算法中影响性能的调优控制开关更少, 这可能是好事,也可能是坏事。直到 Java 7u4,G1 都一直被当作实验版本,它的一些调优 特性直到 Java 7u10 中才提供出来。相对于 Java 7 及之前的版本而言,G1 的性能提升主要 体现在 Java 8 中。G1 将来的工作可能会关注在如何提高它在较小的堆上相对于 CMS 的性 能优势。

+ 选择 Concurrent 收集器时,如果堆较小,推荐使用 CMS 收集器。

+ 简单粗暴 地设置一个特别大的堆也不是解决问题的方法。GC 停顿消耗的时间取决于堆的大小,如果增大堆的空间,停顿的持续时间也会变长。这种情况下,停顿的频率会变得更少,但是 它们持续的时间会让程序的整体性能变慢。

+ 如果 Full GC 时系统发生内存交换,停顿时间会以正常停顿 时间数个量级的方式增长。类似地,如果使用 Concurrent 收集器,后台线程在回收堆时, 它的速度也可能会被拖慢,因为需要等待从磁盘复制数据到内存,结果导致发生代价昂贵 的并发模式失效。因此,调整堆大小时首要的原则就是永远不要将堆的容量设置得比机器的物理内存还大, 另外,如果同一台机器上运行着多个 JVM 实例,这个原则适用于所有堆的总和。除此之 外,你还需要为 JVM 自身以及机器上其他的应用程序预留一部分的内存空间:通常情况 下,对于普通的操作系统,应该预留至少 1 G 的内存空间。

+ 选择什么样的堆内存大小没有一个硬性的或简单的规则(不过你需要确保设 置的大小是机器可以支持的)。一个经验法则是完成 Full GC 后,应该释放出 70% 的空间
(30% 的空间仍然占用)。为了衡量这个结果,你可以持续运行应用程序,直到其到达稳定 态配置:这时它已经载入了需要缓存的所有对象,或者已经创建了最多的客户端连接数, 诸如此类。之后,使用 jconsole 连接应用程序,强制进行 Full GC,观察 Full GC 结束后 还有多少内存被占用(此外,对于 Throughput 垃圾收集器,如果有日志的话,你可以通过 查询 GC 日志得到对应的数据)。

+ 除非应用程序需要比默认值更大的堆,否则在进行调优时,尽量考虑通 过调整 GC 算法的性能目标(具体内容在下一章介绍),而非微调堆的大小来改善程序性能。

+ 一旦堆的大小确定下来,你(或者 JVM)就需要决定分配多少堆给新生代空间,多少给老 年代空间。我们应该清楚地了解代的划分对性能的影响:如果新生代分配得比较大,垃圾 收集发生的频率就比较低,从新生代晋升到老年代的对象也更少。任何事物都有两面性, 采用这种分配方法,老年代就相对比较小,比较容易被填满,会更频繁地触发 Full GC。 这里找到一个恰当的平衡点是解决问题的关键。

```
-XX:NewRatio=N 设置新生代与老年代的空间占用比率。默认值为 2。
-XX:NewSize=N 设置新生代空间的初始大小。
-XX:MaxNewSize=N 设置新生代空间的最大大小。
-XmnN 将 NewSize 和 MaxNewSize 设定为同一个值的快捷方法。

使用 NewRatio 计算空间的公式: 
    Initial Young Gen Size = Initial Heap Size / (1 + NewRatio)
    
使用 NewSize 标志设定的 新生代大小,其优先级要高于通过 NewRatio 计算出来的新生代大小。NewSize 标志没有默 认的设置。NewSize 不设置的情况下, 初始的新生代大小由 NewRatio 计算出的值决定。
```

+ 试图通过指定新生代的最大及最小值区间的方式调优新生代的结果是十分困难的。如果堆 的大小是固定的(可以通过将 -Xms 和 -Xmx 指定为相等的值实现),通常推荐使用 -Xmn 标 志将新生代也设定为固定大小。

+ JVM 载入类的时候,它需要记录这些类的元数据。从终端用户的角度来看,这些只是 一些“书签”信息。这部分数据被保存在一个单独的堆空间中。在 Java 7 里,这部分空 间被称为永久代(Permgen 或 Permanent Generation),在 Java 8 中,它们被称为元空间
(Metaspace)。

+ 永久代和元空间内保存的信息只对编译器或者 JVM 的运行时有用,这部分信息被称为“类的元数据”。

+ 到目前为止都没有一个能提前计算出程序的永久代 / 元空间需要多大空间的好算法。永久 代或者元空间的大小与程序使用的类的数量成比率相关,应用程序越复杂,使用的对象越 多,永久代或者元空间就越大。使用元空间替换掉永久代的优势之一是我们不再需要对其 进行调整——因为(不像永久代)元空间默认使用尽可能多的空间。

+ 对于永久代而言,可以通过 -XX:PermSize=N、 -XX:MaxPermSize=N 标志调整大小。而元空间的大小可以通过 -XX:MetaspaceSize=N 和 -XX:MaxMetaspaceSize=N 调整。

+ 由于元空间默认的大小是没有作限制的,因此 Java 8(尤其是 32 位系统)的应用可能 由于元空间被填满而耗尽内存。本地内存跟踪器(Native Memory Tracking,NMT)可以帮助诊断这种类型的问题。如果元空间增长得过大,通过设置 MaxMetaspaceSize 你可以调整元空间的上限,将其限制为一个更小的值,不过这又会导 致应用程序最后由于元空间耗尽,发生 OutOfMemoryError 异常。解决这类问题的终极方 法还是定位出为什么类的元空间会变得如此巨大。

+ 如果程序在启动时发生大量 的 Full GC(因为需要载入数量巨大的类),通常都是由于永久代或者元空间发生了大小调 整,因此这种情况下为了改善启动速度,增大初始值是个不错的主意。对于定义了大量类 的 Java 7 应用,同时还需要增大永久代空间的最大值。

+ 虽然名称叫“永久代”,保存在永久代空间中的数据并不能永久保存(元空间这个名字可 能更准确)。尤其是,保存在其中的类像其他的对象一样会经历垃圾回收。

+ 堆转储(参见第 7 章)的信息可以用于诊断存在哪些类加载器,而这些信息反过来可以帮助确定是否存在类加载器的泄漏,最终导致永久代(或者元空间)被耗尽。除此之外,使 用 jmap 和 -permstat 参数(适用于 Java 7)、或者 -clstats 参数(适用于 Java 8)可以输 出类加载器相关的信息。不过这些命令都不是非常稳定,所以不大推荐使用。

+ 除 Serial 收集器之外几乎所有的垃圾收集器使用的算法都基于多线程。启动的线程数由-XX:ParallelGCThreads=N 参数控制。

+ 由于 GC 操作会暂停所有的应用程序线程,JVM 为了尽量缩短停顿时间就必须尽可能地利 用更多的 CPU 资源。这意味着,默认情况下,JVM 会在机器的每个 CPU 上运行一个线 程,最多同时运行 8 个。一旦达到这个上限,JVM 会调整算法,每超出 5/8 个 CPU 启动 一个新的线程。所以总的线程数就是(这里的 N 代表 CPU 的数目): `ParallelGCThreads = 8 + ((N - 8) * 5 / 8)`。

+ 在 8 核或者 CPU 更少的机器上,垃圾收集线程会 100% 地占用机器的 CPU 处理资 源。在拥有更多 CPU、运行了多个 JVM 的机器上,通常出现的问题是有太多的垃圾回收 线程在同时并发运行。

+ 几乎所有的垃圾收集算法中基本的垃圾回收线程数都依据机器上的 CPU 数目计算得出。多个 JVM 运行于同一台物理机上时,依据公式计算出的线程数可能过 高,必须进行优化(减少)。

+ 使用 -XX:-UseAdaptiveSizePolicy 标志可以在全局范围内关闭自适应调整功能(默认情况 下,这个标志是开启的)。如果堆容量的最大、最小值设置成同样的值,与此同时新生代 的初始值和最大值也设置为同样大小,自适应调整的功能会被关闭。不过这时的 Survivor 空间是个例外(即仍然会自适应调整)。

+ 想了解应用程序运行时 JVM 的空间是如何调整的,可以设置 -XX:+PrintAdapti veSizePolicy 标志。开启该标志后,一旦发生垃圾回收,GC 的日志中会包含垃圾回收时 不同的代进行空间调整的细节信息。

+ 通常情况下,我们应该开启自适应调整,因为垃圾回收算法依赖于调整 后的代的大小来达到它停顿时间的性能目标。对于已经精细调优过的堆,关闭自适应调整能获得一定的性能提升。

+ 观察垃圾回收对应用程序的性能影响最好的方法就是尽量熟悉垃圾回收的日志,垃圾回收 日志中包含了程序运行过程中的每一次垃圾回收操作。

+ 多种方法都能开启 GC 的日志功能,其中包括:使用 -verbose:gc 或 -XX:+PrintGC 这两个 标志中的任意一个能创建基本的 GC 日志(这两个日志标志实际上互为别名,默认情况下 的 GC 日志功能是关闭的)。使用 -XX:+PrintGCDetails 标志会创建更详细的 GC 日志。我 们推荐使用 -XX:+PrintGCDetails 标志(这个标志默认情况下也是关闭的);通常情况下使 用基本的 GC 日志很难诊断垃圾回收时发生的问题。除了使用详细的 GC 日志,我们还推 荐使用 -XX:+PrintGCTimeStamps 或者 -XX:+PrintGCDateStamps,便于我们更精确地判断几 次 GC 操作之间的时间。这两个参数之间的差别在于时间戳是相对于 0(依据 JVM 启动的 时间)的值,而日期戳(date stamp)是实际的日期字符串。由于日期戳需要进行格式化, 所以它的效率可能会受轻微的影响,不过这种操作并不频繁,它造成的影响也很难被我们 感知。

+ 使用 -Xloggc:filename 标志也能修改输出 到某个文件。除非显式地使用 -PrintGCDetails 标志,否则使用 -Xloggc 会自动地开启基 本日志模式。使用日志循环(Log rotation)标志可以限制保存在 GC 日志中的数据量;对于需要长时间运行的服务器而言,这是一个非常有用的标志,否则累积几个月的数据很 可能会耗尽服务器的磁盘。通过 -XX:+UseGCLogfileRotation -XX:NumberOfGCLogfiles=N -XX:GCLogfileSize=N 标志可以控制日志文件的循环。默认情况下,UseGCLogfileRotation 标志是关闭的。开启 UseGCLogfileRotation 标志后,默认的文件数目是 0(意味着不作任 何限制),默认的日志文件大小是 0(同样也是不作任何限制)。因此,为了让日志循环功 能真正生效,我们必须为所有这些标志设定值。需要注意的是,如果设定的数值不足 8 KB的话,日志文件的大小会以 8 KB 为单位规整。

+ GC Histogram 能够读入 GC 日志,根据日志文件中的数据生成对应的图表和表格。

+ 使用 jconsole 可以实时监控堆的使用情况。jconsole 的内存面板可以实时查看堆的使用状况。

+ 使用 jconsole 一次只能看到一个分区的使用情况:要么是 Eden 空间,要么是 Survivor 空间,要么是老年代,或者是永久代。

+ 如果你希望使用脚本的方式获取数据,jstat 是理想的工具。jstat 提供了 9 个选项,提供 堆的各种数据;使用 jstat -options 选项能够列出所有这些选项。这其中最常用的一个选 项是 -gcutil,它能够输出消耗在 GC 上的时间,以及每个 GC 区域使用的百分比。其他的 选项能够以 KB 为单位输出各 GC 空间的大小。注意,jstat 接受一个可选的参数,指定每隔多少毫秒重复执行这个命令,这个选项帮助 我们长时间地监控应用程序的垃圾回收过程。

+ GC 日志是分析 GC 相关问题的重要线索;我们应该开启 GC 日志标志 (即使是在生产服务器上)。

+ 对任何一个 Java 应用程序而言,垃圾收集的性能都是其构成整体性能的关键一环。虽然 对大多数的应用程序来说,调优的工作仅仅是选择合适的垃圾收集算法,或者在需要的时候, 增大应用程序的堆空间。更复杂的应用往往需要额外的调优,尤其是针对特定GC算法的调优。

+ 新生代进行垃圾回收时,整个新生代空间要么被 回收,要么被晋升(对象被移动到 Survivor 空间,或者移动到老年代)。

### Throughput 收集器

+ 通常**新生代的垃圾回收发生在 Eden 空间快用尽时**。新生代垃圾收集会把 Eden 空间中的所 有对象挪走:一部分对象会被移动到 Survivor 空间,其他的会被 移动到老年代;正如你看到的,回收之后老年代中保存了更多的对象。当然, 还有大量的对象因为没有任何对象引用而被回收。

+ 为什么有S0和S1两个Survivor内存区？因为对于新生代的收集通常均采用“标记-复制算法”，该算法不会进行内存整理，而是直接对eden区中的对象进行拷贝。在这一思路下，s0和s1是“交替”作为拷贝区存在的，如果只有一个s区，可以思考下会发生什么？。

+ 一次典型的Minor GC输出：

```
// GC发生在程序启动后17.806秒
17.806: [GC 
            // 新生代从227MB降低到了14MB，当前新生代总共占260MB
            [PSYoungGen: 227983K->14463K(264128K)]  
            // 总堆内存从280MB降到66MB，当前总堆内存613MB，总耗时0.0169秒
            [280122K->66610K(613696K), 0.0169320 secs]
            // user代表CPU时间，此处由于使用四个并行线程，因此 4*0.0169320 ~ 0.05
            // real是0.0169320的归整值
            [Times: user=0.05 sys=0.00, real=0.02 secs]
```

+ 老年代垃圾收集会回收新生代中所有的对象(包括 Survivor 空间中的对象)。只有那些有 活跃引用的对象,或者已经经过压缩整理的对象(它们占据了老年代的开始部分)会在老 年代中继续保持,其余的对象都会被回收。

+ 一次典型的Full GC输出：

```
64.546: [Full GC [PSYoungGen: 15808K->0K(339456K)] // 新生代
               [ParOldGen: 457753K->392528K(554432K)] 473561K->392528K(893888K) // 老年代
               [PSPermGen: 56728K->56728K(115392K)], 1.3367080 secs] // 永久代
               [Times: user=4.44 sys=0.01, real=1.34 secs]
```

+ Throughput 收集器的调优几乎都是围绕停顿时间进行的,寻求堆的总体大小、新生代的大 小以及老年代大小之间平衡。

+ 根据以往的经验,如果应用程序在垃圾回 收上消耗总时间的 3% 至 6%,其效果会是相当不错的。

### CMS收集器

+ 一次典型的CMS Minor GC输出：

```
89.853: [GC 89.853: [ParNew: 629120K->69888K(629120K), 0.1218970 secs]
                     1303940K->772142K(2027264K), 0.1220090 secs]
                     [Times: user=0.42 sys=0.02, real=0.12 secs]
```

+ 如果使用 CMS 回收器,老年代空间不会进行压缩整理:老年代空 间由已经分配对象的空间和空闲空间共同组成。容易产生内存碎片，从而导致FullGC。

+ CMS回收过程划分成了好几个阶段，虽然主要的并发回收(Concurrent Cycle)阶段都使用后台线程进行工作,有些阶段还是会暂停所有的应用线程,并因此引入 短暂的停顿。

+ 一次典型的CMS Full GC输出：

```
// 初始标记阶段，应用程序线程停顿
89.976: [GC [1 CMS-initial-mark: 702254K(1398144K)] // 对象占用了老年代空间 1398 MB 中的 702 MB 空间
                     772530K(2027264K), 0.0830120 secs] // 整个堆的 大小为 2027 MB,其中 772 MB 被占用
                     [Times: user=0.08 sys=0.00, real=0.08 secs]
                     
// 标记阶段，应用程序线程不停顿
90.059: [CMS-concurrent-mark-start]
90.887: [CMS-concurrent-mark: 0.823/0.828 secs]
                [Times: user=1.11 sys=0.00, real=0.83 secs]

// 预清理
90.887: [CMS-concurrent-preclean-start]
90.892: [CMS-concurrent-preclean: 0.005/0.005 secs]
             [Times: user=0.01 sys=0.00, real=0.01 secs]

// 重新标记
90.892: [CMS-concurrent-abortable-preclean-start] // 可中断预清理，应用程序不停顿
92.392: [GC 92.393: [ParNew: 629120K->69888K(629120K), 0.1289040 secs] // 新生代GC
             1331374K->803967K(2027264K), 0.1290200 secs]
             [Times: user=0.44 sys=0.01, real=0.12 secs]
94.473: [CMS-concurrent-abortable-preclean: 3.451/3.581 secs] // 可中断预清理，应用程序不停顿
             [Times: user=5.03 sys=0.03, real=3.58 secs]
94.474: [GC[YG occupancy: 466937 K (629120 K)] // 新生代中断标记
94.474: [Rescan (parallel) , 0.1850000 secs]
94.659: [weak refs processing, 0.0000370 secs]
94.659: [scrub string table, 0.0011530 secs]
     [1 CMS-remark: 734079K(1398144K)]
     1201017K(2027264K), 0.1863430 secs]
[Times: user=0.60 sys=0.01, real=0.18 secs]
     
// 清理阶段
94.661: [CMS-concurrent-sweep-start]
95.223: [GC 95.223: [ParNew: 629120K->69888K(629120K), 0.1322530 secs]
             999428K->472094K(2027264K), 0.1323690 secs]
             [Times: user=0.43 sys=0.00, real=0.13 secs]
95.474: [CMS-concurrent-sweep: 0.680/0.813 secs]
             [Times: user=1.45 sys=0.00, real=0.82 secs]
```

+ 新生代发生垃圾回收,同时老年代又没有足够的空间容纳晋升的对象时, CMS垃圾回收就会退化成 Full GC。所有的应用线程都会被暂停,老年代中所有的无效对象都被回收。CMS这一个过程是单线程的。

+ 老年代有足够的空间可以容纳晋升的对象,但是由于空闲空间的碎片化, 导致晋升失败，CMS对老年代空间进行压缩和整理，进而产生Full GC，导致应用程序线程停顿。

+ 默认情况下, CMS 收集器不会对永久代(或元空间)进行收集,因此,它一旦被用尽,就需要进行 Full GC,所有没有被引用的类都会被回收。

+ 调优 CMS 收集器时最要紧的工作就是要避免发生并发模式失效以及晋升失败（即Full GC）。
    
+ 发生并发模式失效往往是由于 CMS 不能以足够快的 速度清理老年代空间:新生代需要进行垃圾回收时,CMS 收集器计算发现老年代没有足够 的空闲空间可以容纳这些晋升对象,不得不先对老年代进行垃圾回收。

### G1垃圾收集器

### 堆内存分析

+ `jcmd <process_id> GC.class_histogram`可以获取到应用的**堆直方图**，输出中只包含当前活跃对象象：

```
num     #instances       #bytes  class name
      ---------------------------------------------
￼1:       789087     31563480  java.math.BigDecimal
2:       237997     22617192  [C
3:       137371     20696640  <constMethodKlass>
4:       137371     18695208  <methodKlass>
5:       13456      15654944  <constantPoolKlass>
6:       13456      10331560  <instanceKlassKlass>
7:       37059      9238848  [B
8:       10621      8363392  <constantPoolCacheKlass>
 ```

`jmap -histo <process_id>`会输出类似的信息，但是既包含活跃对象，也包含死对象（即将被下次Minor GC或者Full GC回收）
 
+ 直方图擅长识别由分配了一两个特定类的过多实例所引发的问题,但是要进行深度分析, 就需要**堆转储**了。

+ 从命令行生成转储文件：

```
jcmd process_id GC.heap_dump /path/to/heap_dump.hprof
或
jmap -dump:live,file=/path/to/heap_dump.hprof process_id
```

jmap 中包含 live 选项,这会在堆被转储之前强制执行一次 Full GC;jcmd 默认就会这 么做。如果因为某些原因,你希望包含其他对象(即死对象),可以在 jcmd 命令的最后加 上 -all。

+ jhat: jhat这是最原始的堆分析工具。它会读取堆转储文件,并运行一个小型的 HTTP 服务器,该 服务器允许你通过一系列网页链接查看堆转储信息。

+ jvisualvm: 可以从一个运行中的程序获得堆转储文件,也可以 打开之前生成的堆转储文件。在这里,我们可以浏览堆,检查最大的保留对象,以及执 行任意针对堆的查询。

+ mat: 开源的 EclipseLink 内存分析器工具(EclipseLink Memory Analyzer Tool,mat)可以加 载一个或多个堆转储文件并执行分析。它可以生成报告,向我们建议可能存在问题的地 方;也可以用于浏览堆,并对堆执行类 SQL 的查询。

+ 一个对象的**保留内存**,是指回收该对象可以释放出的内存量。

+ 一个对象的**浅大小**,指的是该对象本身的大小。如果该对象包含一个指向另一个对象的引用,4 字节或 8 字节的引用会计算在内,但是目标对象的大小不会包含进来。
 
+ 一个对象的**深大小**则包含那些对象的大小。深大小与保留大小的区别在于那些存在共享的对象。

+ GC 根是一些系统对象,其中保存着一些 (通过一个较长的由其他对象组成的链条)指向问题中对象的静态和全局引用。它们通常 来自在系统或 bootstrap 类路径下加载的某个类中的静态变量,其中包括 Thread 类和所有的活跃线程;线程保留对象,或是通过其线程局部变量,或是通过目标 Runnable 对象(或者在存在 Thread 的子类的情况下,通过子类中包含的任何其他引用)来引用。

+ 任何给定的对象都可能有多个 GC 根。

+ 了解􏰀􏰁哪些对象在消耗􏰂􏰃􏰄􏰅􏰆内存，是优化内存使用的第一步。

+ 直方图对于识别由某一类型对象创建过多导致的内存问题，很直观。

+ 堆转储分析是分析内存问题最根本的方式，需要耐心分析。

+ Java抛出OutOfMemoryError分为四种情况：

1. Java原生内存不够，常见的此时无法创建新的线程
2. 永久代（Java7以前）或元空间（Java8）不够，对于那些使用字节码动态生成类的程序而言，更容易产生此类问题。
3. Java堆本身内存不够，应用中的活跃对象过多
4. Java执行GC耗时太久，
 
<blockquote>
对于第四种情况，需要满足如下**所有条件**才能触发：

1. 花在Full GC上的时间超􏱸􏵃出了-XX:GCTimeLimit=N􏰋设􏰌􏵄定的值􏵅，改值默认为􏱖􏵆􏴺􏵅􏰫98，即超过98%的时间。
2. 一次Full GC的量回收的内存量小于-XX:GCHeapFreeLimit=N，改值默认为2，即少于2%的内存。
3. 上面两个条件连续5次Full GC都成立。
4. -XX:+UseGCoverhead-Limit值设置为true，该值默认为true。
</blockquote>
 
+ MAT中内置了一个功能，可以对比两个内存dump文件的差别。

+ 自动dump堆内存文件的设置：

```
1. -XX:+HeapDumpOnOutOfMemoryError
2. -XX:+HeapDumpPath=<path>
3. -XX:+HeapDumpOnFullGC
4. -XX:+HeapDumpBeforeFullGC

为了在问题发生时，有足够的信息寻找原因，即使在生产环境，仍然建议打开这些设置。
```

+ 集合是引发内存溢出很常见的一个原因：不断插入元素，但从不释放。一种选择是插入对象时使用弱引用或软引用。

+ 减少内存的三种方式：减少对象大小、对象延迟初始化、使用规范化对象。

+ 一般不会在线程安全的代码上引入延迟初始化，这可能加重同步性能成本。

+ 对象重用的两种常见方式：对象池和线程局部变量。这两种技术，对于GC都是不友好的。

+ Full GC的效率与老年代中**对象的数量**成正比，其影响比**堆的大小**更多，总的来说，长生命周期的对象越多越久，GC效率越差。因此，应该**仅仅考虑重用初始化成本非常高的对象**，常见的初始化成本高的对象如下：线程、JDBC池、EJB池、大数组、原生NIO buffer（direct buffer）、安全相关类（MessageDigest、Signature）、字符串编解码器、StringBuilder、随机数生成器、ZIP编解码器、网络对象。

+ 使用线程局部对象是避免同步的好方法。比如java7引入了一个ThreadLocalRandom对象，就可以减少Random对象的同步成本。

+ 