---
author: "patrick.unicorn"
output:
  html_document:
    css: ../css/main.css
    highlight: null
    theme: null
---

SQL基础-MySQL
===

* * *

<q>
SQL语句顺序
SELECT FROM WHERE GROUP BY HAVING ORDER BY
</q>

## 语法

+ `_`可以用以匹配单个任意字符。

```
-- 匹配第二个字符为t的项
SELECT ... FROM ... WHERE ... LIKE '_t%'
```

+ 给创建权限

```
GRANT CREATE ON <db> TO <user>
```

+ 库操作

```
CREATE DATABASE database_name;
DROP DATABASE database_name;
USE DATABASE database_name;
```

+ 表操作

```
CREATE TABLE IF NOT EXITS track(
  album CHAR(10) NOT NULL,
  dsk INTEGER NOT NULL,
  -- 联合主键
  PRIMARY KEY (album, dsk)
);
DROP TABLE <name>;

-- 重命名表
ALTER TABLE table_name RENAME TO new_table_name;

-- 删除表数据信息，(相比DELETE)自增字段的初始值也会初始化
TRUNCATE TABLE table_name;

INSERT INTO t_table_0(a, b) SELECT A, B FROM t_table_1; 

-- 显示表的DDL语句
SHOW CREATE TABLE table_name;
```

+ 临时表

临时表主要用于储存中间结果，当前session中断后，临时表会被自动删除。使用`SHOW TABLES`命令时，临时表不会被列出来。

```
CREATE TEMPORARY TABLE SALESSUMMARY ...
DROP TABLE SALESSUMMARY;
```

+ 列操作

```
ALTER TABLE table_name {ADD|DROP|MODIFY} column_name {data_ype};

ALTER TABLE table_name ADD column_name <datatype> DEFAULT <defaultValue>;
ALTER TABLE table_name DROP COLUMN column_name;

-- 把x列重命名为y，类型不变
ALTER TABLE a CHANGE x y INTEGER;

-- 修改列的数据类型，并约束不可空
ALTER TABLE table_name MODIFY column_name datatype NOT NULL;
-- 修改列的数据类型，并约束可空
ALTER TABLE table_name MODIFY column_name datatype NULL;

-- 给表的列添加唯一性约束
ALTER TABLE table_name 
ADD CONSTRAINT MyUniqueConstraint UNIQUE(column1, column2...);

ALTER TABLE table_name DROP CONSTRAINT MyUniqueConstraint;

-- 给表添加主键
ALTER TABLE table_name 
ADD CONSTRAINT MyPrimaryKey PRIMARY KEY (column1, column2...);

-- 删除表的主键
ALTER TABLE t_table DROP PRIMARY KEY;
```

+ 视图操作

```
CREATE VIEW v_name AS SELECT * FROM t_table;
DROP VIEW <name>;
```

+ 索引操作

```
-- 创建a列和b列的聚合索引
CREATE INDEX i_dex ON t_table(a, b);

-- 删除索引
ALTER TABLE table_name DROP INDEX index_name;
```

+ 判定NULL

```
SELECT * FROM t_table WHERE c_column IS NULL;
SELECT * FROM t_table WHERE c_column IS NOT NULL;
```

+ 区间搜索

```
select * from t_test where name BETWEEN 2 AND 3;
-- 等价于
select * from t_test where name >= 2 AND name <=3;
```

+ 分页

```
-- 95行到结尾
SELECT * FROM table LIMIT 95,-1;
SELECT * FROM table LIMIT 5;
--前五行
SELECT * FROM table LIMIT 0,5;
```

## 性能

+ 避免使用SELECT *

+ 避免数字和字符串之间的转换

+ 谨慎设置索引，避免直接在插入更新操作非常频繁的表上设置索引

+ 设置合理索引，避免全表查询；建立的索引能覆盖80%主要的查询，不求全，解决问题的主要矛盾

+ 避免使用模糊匹配

+ 避免使用OR

+ 避免使用子查询，用连接查询替代

+ 合理使用存储过程

+ 使用UNION ALL，而非UNION

+ 能够快速缩小结果集的 WHERE 条件写在前面，如果有恒量条件，也尽量放在前面

+ 能够使用索引的字段尽量进行有效的合理排列，如果使用了联合索引，请注意提取字段的前后顺序

+ 针对索引字段使用 >, >=, =, <, <=, IF NULL和BETWEEN 将会使用索引， 如果对某个索引字段进行 LIKE 查询，使用 LIKE ‘%abc%’不能使用索引，使用 LIKE ‘abc%’ 将能够使用索引

+ 尽量使用exists代替select count(1)来判断是否存在记录，count函数

+ 只有在统计表中所有行数时使用，而且count(1)比count(*)更有效率

+ 如果在SQL里使用了MySQL部分自带函数，索引将失效，同时将无法使用 MySQL 的 Query Cache，比如DATE_FORMAT(), 等，如果使用了 OR 或 IN，索引也将失效

+ 不要过度索引，单表建立的索引不要超过5个，否则更新索引将很耗时

+ 在使用索引字段作为条件时，如果该索引是联合索引，那么必须使用到该索引中的第一个字段作为条件时才能保证系统使用该索引，否则该索引将不会被使用

+ 要注意索引的维护，周期性重建索引

+ 使用 Explain/ DESC 来分析SQL的执行情况

```
Type:类型，是否使用了索引还是全表扫描, const,eg_reg,ref,range,index,ALL 
Key:实际使用上的索引是哪个字段 Ken_len: 真正使用了哪些索引，不为 NULL 的就是真实使用的索引
Ref:显示了哪些字段或者常量被用来和 key 合从表中查询记录出来 
Rows:显示了MySQL认为在查询中应该检索的记录数 
Extra:显示了查询中MySQL的附加信息，关心Using filesort 和 Using temporary，性能杀手
```

+ 使用 SHOW PROCESSLIST 来查看当前MySQL服务器线程执行情况，是否锁表，查看相应的SQL语句

+ 通过开启慢查询，可以定位慢SQL

+ 表字符集选择UTF8 ，如果需要存储emoj表情，需要使用UTF8mb4(MySQL 5.5.3以后支持)

+ 变长字符串尽量使用varchar varbinary

+ 不在数据库中存储图片、文件等

+ 库名、表名、字段名不使用保留字；库名、表名、字段名、索引名使用小写字母，以下划线分割 ，需要见名知意；库表名不要设计过长，尽可能用最少的字符表达出表的用途

+ 使用varchar存储变长字符串 ，当然要注意varchar(M)里的M指的是字符数不是字节数；使用UNSIGNED INT存储IPv4 地址而不是CHAR(15) ，这种方式只能存储IPv4，存储不了IPv6

+ 索引这个东西是一把双刃剑，在加速读的同时也引入了很多额外的写入和锁，降低写入能力，这也是为什么要控制索引数原因。

+ 避免使用大表的JOIN

+ UPDATE、DELETE语句不使用LIMIT ，容易造成主从不一致

+ 主从时延问题：

```
原因：

一般都会做读写分离，其实从库压力反而比主库大／从库读写压力大非常容易导致延时。

解决方案：

1. 首先定位延时瓶颈
2. 如果是IO压力，可以通过升级硬件解决，比如替换SSD等
3. 如果IO和CPU都不是瓶颈，非常有可能是SQL单线程问题，解决方案可以考虑刚才提到的并行复制方案
4. 如果还有问题，可以考虑sharding拆分方案
```

+ 单表数据大小主要依据表的查询场景，如果仅仅是单表查询通常满足【1亿以下且4GB以下】；如果场景更多是多表连接查询，那么多个连接表的大小总量应满足【1亿以下且4GB以下】。查询数据表的大小：

```
SELECT 
    table_name AS `Table`, 
    round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB` 
FROM information_schema.TABLES 
WHERE table_schema = "DB_NAME"
    AND table_name = "TABLE_NAME";
```